name: "Crear una Issue"
description: "Plantilla para crear una nueva issue"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Título del Issue
        (Usar el formato: Nombre WI / Fakenodo / Docs: título tarea)

  - type: input
    id: issue-title
    attributes:
      label: "Título del Issue"
      description: "Descripción clara y concisa del problema o tarea. Usar el formato indicado."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Descripción"
      description: "Detalle completo del problema, mejora o tarea. Incluir contexto, objetivo y detalles relevantes."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Criterios de Aceptación (si aplica)"
      description: "Definir las condiciones necesarias para considerar el issue resuelto."
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Pasos para Reproducir (solo para bugs)"
      description: "Lista detallada de pasos para reproducir el problema, en caso de tratarse de un error."
    validations:
      required: false

  - type: dropdown
    id: tags
    attributes:
      label: "Etiquetas"
      description: "Seleccionar una o varias etiquetas para clasificar el issue."
      multiple: true
      options:
        - bug
        - WI
        - fakenodo
        - documentation
        - workflow
        - test
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: "Fecha Límite (si aplica)"
      description: "Especificar una fecha límite para completar el issue, si corresponde."
    validations:
      required: false




