name: "Issue Template"
description: "Plantilla estandarizada para crear issues con consistencia y claridad"
title: "Nombre WI / Fakenodo / Docs: título tarea"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Descripción**  
        Detalle completo del problema, mejora o tarea. Incluye contexto, objetivo y detalles relevantes que permitan entender de qué se trata el issue.

  - type: textarea
    id: descripcion
    attributes:
      label: "Descripción"
      description: "Proporcione una descripción detallada del problema o tarea"
      placeholder: "Incluye contexto, objetivo y detalles relevantes"

  - type: textarea
    id: criterios_aceptacion
    attributes:
      label: "Criterios de Aceptación (si aplica)"
      description: "Define las condiciones que deben cumplirse para considerar el issue resuelto"
      placeholder: "Condiciones para la resolución del issue"

  - type: textarea
    id: pasos_para_reproducir
    attributes:
      label: "Pasos para Reproducir (en caso de un bug)"
      description: "Lista detallada de pasos para reproducir el problema si es un error"
      placeholder: "1. Paso uno\n2. Paso dos\n3. Paso tres"

  - type: checkboxes
    id: etiquetas
    attributes:
      label: "Etiquetas"
      description: "Clasifica el issue utilizando las etiquetas adecuadas"
      options:
        - label: "bug"
        - label: "WI"
        - label: "fakenodo"
        - label: "documentation"
        - label: "workflow"

  - type: users
    id: asignados
    attributes:
      label: "Asignados"
      description: "Define al miembro del equipo responsable de la tarea, si corresponde"

  - type: date
    id: fecha_limite
    attributes:
      label: "Fecha Límite (si aplica)"
      description: "Fecha específica en la que debe completarse el issue"
